name: random_number
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  numbers_to_words_russian: ^1.0.2
  cupertino_icons: ^1.0.2
  keyboard_dismisser: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "assets"
  image_path: "assets/random.png"
  min_sdk_android: 21 # android min sdk min:16, default 21